### ISSUE TITLE
Dockerfile.generated race with same Dockerfile and different build args

### ISSUE THREAD

**Issue by grugnog** [cloud66-oss/habitus#113]
build.yml looks something like:
```
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    v1:
      name: v1
      dockerfile: Dockerfile
      args:
        version: 1
    v2:
      name: v2
      dockerfile: Dockerfile
      args:
        version: 2
```

What happens is that the Dockerfile.generated is the same filename and path. Both builds proceed in parallel (using whichever file was created last). As soon as the first build finishes the Dockerfile.generated is removed and so the second build errors with "Build for step v2:latest failed due to remove dir/Dockerfile.generated: no such file or directory".

I think the solution for this would be to either encode the build args in the filename for Dockerfile.generated (probably in the form of a hash) or generate a random token to the file and track that through the lifecycle of the build.
