### ISSUE TITLE
[Feature Request] Ability to build dockerfile located inside sub-directories

### ISSUE THREAD

**Issue by dduportal** [cloud66-oss/habitus#83]
Hello!

Thanks for your work on this project!

I would want to replace my handmade Makefile by habitus to build my docker images library, which are all located on a single repository (inter-dependencies).

Each Dockerfile is stored in a dedicated folder (goal: only upload the context of a given image when building it).

With the current `habitus` version (`v1.0.1`),  the `COPY` directives are exiting in error with the following message: 
```
Build for step test failed due to COPY failed: stat /var/lib/docker/tmp/docker-builder225133515/entrypoint.sh: no such file or directory 
```

If I move (and adapt) my build.yml into the image directory, then it works as expected.
I can also use the "artifacts" instruction to make it work, but it would make my Dockerfile too tightened to habitus (and not feature-complete).

Based on the documentation, I understand that the flag "d" passed to the commandline give the working directory for habitus. Haven't read the code yet, but I suppose this working directory is uploaded to the remote docker engine, with the generated Dockerfiles inside. But the content of sub directories is not, leading in this error.

It would nice to be able to specify sub directories for the `dockerfile` instruction in the `build.yml`.
It would allow the build.yml to "orchestrate" the build, but keeping a logical isolation for the source code, as well as allowing more complex build patterns using git subtrees, virtual FS views, etc.

I've put an example of expectation for this feature below:

* Directory tree view:
```
$ tree
.
├── build.yml
├── test
│   ├── Dockerfile
│   └── entrypoint.sh
```

* `build.yml`:
```

build:
  version: 2016-03-14 # version of the build schema.
  steps:
    test:
      name: test
      dockerfile: test/Dockerfile
```

* `Dockerfile`:
```
FROM alpine:3.7
RUN apk add --no-cache tini

COPY ./entrypoint.sh /entrypoint.sh

ENTRYPOINT ["tini","-g","--","sh"]
CMD ["/entrypoint.sh"]

```

Tell me if this is clear, or if you need more information, review, or whatever help on this.

**Comment by mumoshu** [comment]
@dduportal Hi! Have you tried setting `work_dir` in your `build.yaml` like:

```yaml
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    test:
      name: test
      dockerfile: test/Dockerfile
      work_dir: test/
```

I suppose it would work as far as I could see from [the implementation](https://github.com/cloud66/habitus/blob/master/build/manifest.go#L90) 😉
